import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Card } from 'react-bootstrap';
import Header from './components/Header';
import About from './components/About';
import Project from './components/Project';
import Contact from './components/Contact';

export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>Frontend Developer </title>
        <meta name="description" content="Generated by create next app" />
        <meta name='theme-color' content='#333a45' />
        <meta name='og:type' content='wesbite'/>
        <meta name='og:image' content='/assets/profile.jpg' />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Card className={styles.card}>
          <Card.Body>
          <Header/>
          <About/>
          <Contact/>
          <Project/>
          </Card.Body>
        </Card>
      </main>
    </div>
  )
}
